package com.example.myapp.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.myapp.Daobean;

import com.example.myapp.dao.DaobeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daobeanDaoConfig;

    private final DaobeanDao daobeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daobeanDaoConfig = daoConfigMap.get(DaobeanDao.class).clone();
        daobeanDaoConfig.initIdentityScope(type);

        daobeanDao = new DaobeanDao(daobeanDaoConfig, this);

        registerDao(Daobean.class, daobeanDao);
    }
    
    public void clear() {
        daobeanDaoConfig.clearIdentityScope();
    }

    public DaobeanDao getDaobeanDao() {
        return daobeanDao;
    }

}
